[project]
name = "my_minipack"
version = "0.0.1"
authors = [
  { name="Ayoub ABOUNAKIF", email="aabounak@student.1337.ma" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ayoubabounakif/42cursus-python/module_02/ex04/"
"Bug Tracker" = "https://github.com/ayoubabounakif/42cursus-python/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
